steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'asia-southeast1-docker.pkg.dev/ml-cve/ml-cve-run/ml-cve-run:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/ml-cve/ml-cve-run/ml-cve-run:latest']