FROM python:3.12-slim

# Install the required library
RUN apt-get update && apt-get install -y libgl1-mesa-glx
# Install necessary libraries
RUN apt-get update && apt-get install -y libglib2.0-0

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

RUN apt-get update && apt-get install -y git vim net-tools build-essential google-cloud-cli=473.0.0-0

# Install Python dependencies
COPY requirements.txt /code/requirements.txt
RUN pip install -r /code/requirements.txt

WORKDIR /code

# Copy the rest of the code (optional, for initial build)
COPY . /code

#ENV PYTHONPATH=/code/src