apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-action-cve-run
spec:
  template:
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/github-action-cve/cloud-run-source-deploy/cloud-run-source-deploy:latest
          env:
            - name: SERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          args: ["python", "main.py"]