apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ml-run-service
spec:
  template:
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/ml-cve/ml-cve-run/ml-cve-run:latest
          env:
            - name: SERVICE_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          args: ["python", "main.py"]